 angular.module('app').config(function ($translateProvider) {
  $translateProvider.translations('en', {

   EditProfile : 'EditProfile',
   Username : 'Username',
   password : 'Password',
   Confirmpassword : 'Confirm Password',
   Firstname : 'Firstname',
   Lastname : 'Lastname',
   Gender : 'Gender',
   Male : 'Male',
   Female : 'Female',
   Email : 'Email',
   Age : 'Age',
   Weight : 'Weight',
   Height : 'Height',
   Type : 'Type',
   Complication : 'Complication',
   Disease : 'Disease',
   DrugAllergy : 'Drug allergy',
   EmailDoctor : 'Email Doctor',
   Save : 'Save',
   Delete : 'Delete',
   Selecttype : 'Select type',
   insulin : 'insulin',
   notinsulin : 'no insulin',
   SelectComplication : 'SelectComplication',
   NoComplication : 'No Complication',
   retinopathy : 'retinopathy',
   nephropathy : 'nephropathy',
   neuropathy : 'neuropathy',
   DiabeticUlcer : 'Diabetic ulcer',
   DiabeticFoot : 'Diabetic foot',
   SelectDisease : 'Select Disease',
   NoDisease : 'No Disease',
   CardiovascularDisease : 'Cardiovascular Disease',
   HighBloodPressure : 'High blood pressure',
   kidneyDisease : 'kidney disease',
   peripheralNeuropathyDisease : "peripheral neuropathy Disease",
   EyeDisease : 'Eye disease',
   Yes : 'Yes',
   No : 'No',

   Recordsugar: 'Record sugar',
   SymptomsDiabetes : 'Symptoms Diabetes',
   RecordSymptoms : 'Record Symptoms',
   medicalrecord : 'medical record tracking in diabetes',
   date : 'Date',
   Sugarblood : 'Sugar blood',
   BloodPressure : 'Blood pressure',
   Cholesterol : 'Cholesterol',
   weight : 'Weight',
   TakePicture : '*** Take a picture from sugar blood machine.',
   save : 'Save',
   Cancel : 'Cancel',
   history : 'History',
   Records : 'Records',
   showgraph : 'show graph',
   SugarmgdL : 'Sugar blood (mg/dL)',
   BloodpressureMmHg : 'Blood pressure (MmHg.)',
   CholesterolmgdL : 'Cholesterol (mg/dL)',
   Weightkg : 'Weight (kg.)',


   Addfood: 'Add food',
   Name : 'Name',
   ServingSize : 'Serving Size',
   Sugars : 'Sugars',
   TotalFat : 'Total Fat',
   sodium : 'sodium',
   Protein : 'Protein',
   Calories : 'Calories',

   ShowFood : 'Show Food',
   Detail1 : 'You should consume no more than 40 grams of sugar, or 8 teaspoons per day.',
   Detail2 : 'Diabetics should eat no more than 1600-2000 calories per day.',
   Notice : 'Notice',

   Nutrition : 'Nutrition',
   Nutrients : 'Nutrients',
   Today : 'Today',
   Sugar : 'Sugar',
   Carbohydrates : 'Carbohydrates',
   Fat : 'Fat',
   Fiber : 'Fiber',

   Share : 'Share',
   SendEmail : 'Send E-mail',
   toYourDoctor : 'to your doctor',
   From : 'From',
   Content : 'Content',


   Welcome : 'Welcome',
   General: 'General',
   LatestSugar : 'Latest Sugar :',
   SugarGraph : 'Sugar Graph',
   Thegraphshowsthebloodsugar : 'The graph shows the blood sugar.',

   Changelanguage: 'Change language',
   Logout:'Logout',





    FOO: 'This is a paragraph.',
    BUTTON_LANG_EN: 'english',
    BUTTON_LANG_TH: 'thai'
  });
   
  $translateProvider.translations('th', {
   
   EditProfile : 'แก้ไขข้อมูลส่วนตัว',
   Username : 'ชื่อผู้ใช้',
   password : 'รหัสผ่าน',
   Confirmpassword : 'ยืนยันรหัสผ่าน',
   Firstname : 'ชื่อ',
   Lastname : 'นามสกุล',
   Gender : 'เพศ',
   Male : 'ชาย',
   Female : 'หญิง',
   Email : 'อีเมล์',
   Age : 'อายุ',
   Weight : 'น้ำหนัก',
   Height : 'ส่วนสูง',
   Type : 'ชนิดเบาหวาน',
   Complication : 'ภาวะแทรกซ้อน',
   Disease : 'โรค',
   DrugAllergy : 'การแพ้ยา',
   EmailDoctor : 'อีเมล์ของแพทย์',
   Save : 'บันทึก',
   Delete : 'ลบ',
   Selecttype : 'เลือกชนิด',
   insulin : 'พึ่งอินซูลิน',
   notinsulin : 'ไม่พึ่งอินซูลิน',
   SelectComplication : '--- เลือก ----',
   NoComplication : 'ไม่มีภาวะแทรกซ้อน',
   retinopathy : 'ภาวะเบาหวานขึ้นจอตา',
   nephropathy : 'โรคไตจากเบาหวาน',
   neuropathy : 'โรคระบบประสาท',
   DiabeticUlcer : 'แผลเบาหวาน',
   DiabeticFoot : 'ภาวะแทรกซ้อนของเท้า',
   SelectDisease : 'เลือกโรค',
   NoDisease : 'ไมมีโรค',
   CardiovascularDisease : 'โรคระบบหัวใจหลอดเลือด',
   HighBloodPressure : 'ความดันโลหิตสูง',
   kidneyDisease : 'โรคไตเรื้อรัง',
   peripheralNeuropathyDisease : 'โรคระบบประสาทส่วนปลาย',
   EyeDisease : 'โรคทางตา',
   Yes : 'ใช่',
   No : 'ไม่ใช่',

   Recordsugar: 'บันทึกน้ำตาล',
   SymptomsDiabetes : 'อาการเบาหวาน',
   RecordSymptoms : 'บันทึกอาการ',
   medicalrecord : 'บันทึกทางการแพทย์ในโรคเบาหวาน',
   date : 'วันที่',
   Sugarblood : 'ระดับน้ำตาล',
   BloodPressure : 'ความดันโลหิต',
   Cholesterol : 'คอเลสเตอรอล',
   weight : 'น้ำหนัก',
   TakePicture : '*** ถ่ายภาพจากเครื่องวัดระดับน้ำตาลในเลือด',
   save : 'บันทึก',
   Cancel : 'ยกเลิก',
   history : 'ประวัติ',
   Records : 'บันทึก',
   showgraph : 'แสดงกราฟ',
   SugarmgdL : 'ระดับน้ำตาล (มก./ดล.)',
   BloodpressureMmHg : 'ความดันโลหิต (มม. ปรอท.)',
   CholesterolmgdL : 'คอเลสเตอรอล (มก./ดล.)',
   Weightkg : 'น้ำหนัก (กก.)',

   Addfood: 'เพิ่มอาหาร',
   Name : 'ชื่อ',
   ServingSize : 'หนึ่งหน่วยบริโภค',
   TotalFat : 'ไขมันทั้งหมด',
   sodium : 'โซเดียม',
   Protein : 'โปรตีน',
   Calories : 'แคลลอรี่',
   Sugars : 'น้ำตาล',

   
   ShowFood : 'แสดงข้อมูลอาหาร',
   Detail1 : 'คุณควรใช้น้ำตาลไม่เกิน 40 กรัมหรือ 8 ช้อนชาต่อวัน',
   Detail2 : 'ผู้ป่วยโรคเบาหวานควรกินอาหารไม่เกิน 1600-2000 แคลอรี่ต่อวัน',
   Recommendations : 'ข้อแนะนำ',

   Nutrition : 'โภชนาการ',
   Nutrients : 'สารอาหาร',
   Today : 'วันนี้',
   Sugar : 'น้ำตาล',
   Carbohydrates :'คาร์โบไฮเดรต',
   Fat : 'ไขมัน',
   Fiber : 'เส้นใยอาหาร',

   Share: 'แชร์',
   SendEmail : 'ส่งอีเมล์',
   toYourDoctor : 'ถึงแพทย์ของคุณ',
   From : 'จาก',
   Content : 'เนื้อหา',



   Welcome: 'ยินดีต้อนรับ',
   General: 'ทั่วไป',
   LatestSugar : 'ระดับน้ำตาลล่าสุด :',
   SugarGraph : 'Sugar Graph',
   Thegraphshowsthebloodsugar : 'กราฟแสดงระดับน้ำตาล',

   
   Changelanguage: 'เปลี่ยนภาษา',
   Logout:'ออกจากระบบ',


      FOO: 'Dies ist ein Paragraph.',
      BUTTON_LANG_EN: 'english',
      BUTTON_LANG_TH: 'thai'
});
  $translateProvider.preferredLanguage('en');
});